apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./manifests/namespace.yaml
  - ./manifests/postgres/pvc.yaml
  - ./manifests/postgres/deployment.yaml
  - ./manifests/postgres/service.yaml
  - ./manifests/redis/deployment.yaml
  - ./manifests/redis/service.yaml
  - ./manifests/api/deployment.yaml
  - ./manifests/api/service.yaml
  - ./manifests/web/deployment.yaml
  - ./manifests/web/service.yaml
  - ./manifests/scanner/deployment.yaml
  - ./manifests/worker/deployment.yaml
  - ./manifests/worker/service.yaml
