{{- if .Values.grpc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elder.fullname" . }}-grpc
  labels:
    {{- include "elder.labels" . | nindent 4 }}
    app.kubernetes.io/component: grpc
  {{- with .Values.grpc.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.grpc.service.type }}
  ports:
    - port: {{ .Values.grpc.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "elder.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grpc
{{- end }}
