{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "elder.fullname" . }}
  labels:
    {{- include "elder.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "elder.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "elder.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.api.service.targetPort }}
    - protocol: TCP
      port: {{ .Values.grpc.service.port }}
    - protocol: TCP
      port: {{ .Values.envoy.service.port }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "elder.selectorLabels" . | nindent 10 }}
  {{- if .Values.postgresql.enabled }}
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
    ports:
    - protocol: TCP
      port: 5432
  {{- end }}
  {{- if .Values.redis.enabled }}
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
    ports:
    - protocol: TCP
      port: 6379
  {{- end }}
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
{{- end }}
