# Prometheus configuration for Elder

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'elder'
    environment: 'development'

# Scrape configurations
scrape_configs:
  # Elder API metrics
  - job_name: 'elder-api'
    static_configs:
      - targets: ['api:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 30s

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 30s
