"""Shared helpers for documents routes."""

from __future__ import annotations

import html
import logging
import re
from typing import Any

logger = logging.getLogger(__name__)


def identity_in_tenant(db: Any, identity_id: int | None, tenant_id: int) -> bool:
    """Return True if identity_id is unset or belongs to tenant_id.

    Guards against cross-tenant IDOR whenever an identity_id is accepted from a
    request body (document visibility_users, ...).
    A None id is treated as valid (the reference is simply absent).
    """
    if identity_id is None:
        return True
    return (
        db((db.identities.id == identity_id) & (db.identities.tenant_id == tenant_id))
        .select()
        .first()
        is not None
    )


def visibility_users_in_tenant(
    db: Any, visibility_users: list[int] | None, tenant_id: int
) -> bool:
    """Validate all user IDs in visibility_users belong to tenant_id.

    Used when accepting visibility_users from request body to prevent cross-tenant IDOR.
    Returns True if the list is None/empty or all users belong to the tenant.
    """
    if not visibility_users:
        return True

    for user_id in visibility_users:
        if not identity_in_tenant(db, user_id, tenant_id):
            return False

    return True


def sanitize_html(html_content: str) -> str:
    """Sanitize HTML content using a whitelist approach.

    Allows safe tags commonly generated by markdown-it-py:
    - Headers: h1-h6
    - Text formatting: p, strong, em, code, del
    - Lists: ul, ol, li
    - Quotes: blockquote
    - Code blocks: pre
    - Links: a (with href)
    - Images: img (with src, alt)
    - Tables: table, thead, tbody, tr, th, td
    - Misc: hr, br

    Attributes allowed:
    - href on <a> (validated as safe URL)
    - src, alt on <img>
    - class (for language hints in code blocks from markdown-it)

    All other tags and attributes are stripped.
    """
    if not html_content:
        return ""

    # Allowed tags and their permitted attributes
    allowed_tags = {
        "h1": [],
        "h2": [],
        "h3": [],
        "h4": [],
        "h5": [],
        "h6": [],
        "p": [],
        "strong": [],
        "em": [],
        "code": ["class"],
        "del": [],
        "ul": [],
        "ol": [],
        "li": [],
        "blockquote": [],
        "pre": [],
        "a": ["href", "title"],
        "img": ["src", "alt", "title"],
        "table": [],
        "thead": [],
        "tbody": [],
        "tr": [],
        "th": [],
        "td": [],
        "hr": [],
        "br": [],
    }

    # Simple regex-based sanitizer:
    # 1. Find all HTML tags
    # 2. Check if they're in allowed list
    # 3. If not, strip them or escape

    def is_safe_url(url: str) -> bool:
        """Check if URL is safe (relative or http/https)."""
        if not url:
            return False
        # Allow relative URLs and common protocols
        if url.startswith(("#", "/", ".")):
            return True
        if url.startswith(("http://", "https://", "mailto:")):
            return True
        return False

    def filter_tag(match):
        """Process matched HTML tag."""
        full_tag = match.group(0)
        tag_content = match.group(1)

        # Parse tag name and attributes
        parts = tag_content.split(None, 1)
        if not parts:
            return ""

        tag_name = parts[0].lower().rstrip("/")

        # Check if tag is allowed
        if tag_name not in allowed_tags:
            return ""

        # If it's a self-closing tag or closing tag, allow it
        if tag_name in ("hr", "br") or tag_content.startswith("/"):
            return full_tag

        # Parse attributes
        if len(parts) < 2:
            return f"<{tag_name}>"

        attr_string = parts[1]
        if attr_string.endswith("/"):
            attr_string = attr_string[:-1]

        allowed_attrs = allowed_tags[tag_name]
        filtered_attrs = []

        # Extract attributes using regex
        attr_pattern = r'(\w+)\s*=\s*["\']?([^"\'>\s]+)["\']?'
        for attr_match in re.finditer(attr_pattern, attr_string):
            attr_name = attr_match.group(1).lower()
            attr_value = attr_match.group(2)

            # Check if attribute is allowed
            if attr_name not in allowed_attrs:
                continue

            # Additional validation for specific attributes
            if attr_name == "href":
                if not is_safe_url(attr_value):
                    continue
                # HTML-escape the URL value
                attr_value = html.escape(attr_value)
                filtered_attrs.append(f'href="{attr_value}"')
            elif attr_name == "src":
                if not is_safe_url(attr_value):
                    continue
                attr_value = html.escape(attr_value)
                filtered_attrs.append(f'src="{attr_value}"')
            elif attr_name in ("alt", "title", "class"):
                # HTML-escape text attributes
                attr_value = html.escape(attr_value)
                filtered_attrs.append(f'{attr_name}="{attr_value}"')

        if filtered_attrs:
            return f"<{tag_name} {' '.join(filtered_attrs)}>"
        else:
            return f"<{tag_name}>"

    # Sanitize: replace disallowed tags with empty string, keep allowed ones
    # This regex matches opening tags like <tag attr="value"> and closing tags </tag>
    tag_pattern = r"<(/?)(\w+[^>]*)>"
    sanitized = re.sub(tag_pattern, filter_tag, html_content)

    return sanitized


def slugify(title: str) -> str:
    """Convert title to URL-safe slug.

    Args:
        title: Article title

    Returns:
        URL-safe slug
    """
    slug = title.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[-\s]+", "-", slug)
    return slug.strip("-")
