apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elder
resources:
  - ../../base
  - ingress.yaml
images:
  - name: elder-api:alpha-latest
    newName: localhost:32000/elder-api
    newTag: alpha-latest
  - name: elder-web:alpha-latest
    newName: localhost:32000/elder-web
    newTag: alpha-latest
  - name: elder-scanner:alpha-latest
    newName: localhost:32000/elder-scanner
    newTag: alpha-latest
  - name: elder-worker:alpha-latest
    newName: localhost:32000/elder-worker
    newTag: alpha-latest
labels:
  - includeSelectors: true
    pairs:
      environment: alpha
