#!/usr/bin/env python3
"""Regenerate openapi/v4.yaml from the app's live quart-schema definitions.

Builds the Quart app (same factory the test suite uses), pulls the
OpenAPI 3.1 dict quart-schema already assembles from every
``@validate_request``/``@validate_response`` decorated route
(``app.extensions["QUART_SCHEMA"].openapi_provider.schema()`` — the exact
call quart-schema's own ``/openapi.json`` route and `quart schema` CLI
command use internally), and writes it to ``openapi/v4.yaml`` as a static
file. Static, not a live route: the public docs/spec endpoints stay
disabled (``openapi_path=None`` in ``apps/api/main.py``'s ``QuartSchema()``
call) per security.md's "docs/spec endpoints MUST be authenticated, one
exception: the login endpoint" — this script is a build-time artifact, not
a runtime surface.

Coverage is partial by design at this stage: only routes decorated with
``@validate_request``/``@validate_response`` get rich request/response
schemas (~51 endpoints as of the audit-remediation pass); undecorated
routes still appear as bare paths with no schema. That is an accepted
baseline (R4 finding) — coverage grows as more routes adopt
``@validate_response``, not a blocker for this spec's existence.

Usage:
    python3 scripts/generate_openapi_spec.py
    make openapi-spec   # same thing, via the containerized toolchain

Requires the same env quart-schema/create_app already need at import time
(DATABASE_URL, REDIS_URL) — run inside elder-test:3.13 like the test
suite, or against a local dev DATABASE_URL/REDIS_URL.
"""

import asyncio
import json
import os
import sys

import yaml

# Add parent directory to path (matches scripts/seed_cloud_discovery.py)
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from apps.api.main import create_app  # noqa: E402

OUTPUT_PATH = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "openapi", "v4.yaml")
)


async def _build_schema() -> dict:
    """Build the app and extract quart-schema's OpenAPI dict under an app context.

    Quart's ``app_context()`` is an async context manager, so this must run
    inside an event loop rather than at plain module/script scope. The
    round trip through ``app.json.dumps``/``json.loads`` — the same
    serializer quart-schema's own ``/openapi.json`` route uses — collapses
    ``defaultdict``/enum/etc. into plain JSON-safe ``dict``/``list``/``str``
    so the YAML dump below is standard, portable YAML (no ``!!python/...``
    tags), not a `yaml.dump` on live Python containers.
    """
    app = create_app("testing")
    async with app.app_context():
        raw_schema = app.extensions["QUART_SCHEMA"].openapi_provider.schema()
        return json.loads(app.json.dumps(raw_schema))


def main() -> None:
    """Generate openapi/v4.yaml and print a short coverage summary."""
    schema = asyncio.run(_build_schema())

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

    header = (
        "# Generated by scripts/generate_openapi_spec.py — DO NOT EDIT BY HAND.\n"
        "# Regenerate: make openapi-spec\n"
        "#\n"
        "# Partial coverage baseline (R4 finding, audit-remediation pass):\n"
        "# only @validate_request/@validate_response routes get full\n"
        "# request/response schemas; other routes appear as bare paths.\n"
    )

    with open(OUTPUT_PATH, "w") as fh:
        fh.write(header)
        yaml.safe_dump(schema, fh, sort_keys=False, default_flow_style=False, width=100)

    paths = schema.get("paths", {})
    documented = sum(
        1
        for methods in paths.values()
        for op in methods.values()
        if isinstance(op, dict) and (op.get("requestBody") or op.get("responses"))
    )
    print(f"Wrote {OUTPUT_PATH}")
    print(
        f"Paths: {len(paths)}, schemas: {len(schema.get('components', {}).get('schemas', {}))}"
    )
    print(f"Operations with request/response schema info: {documented}")


if __name__ == "__main__":
    main()
