apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elder
namePrefix: beta-
resources:
- ../../base
replicas:
- count: 2
  name: flask-backend
images:
- name: registry-dal2.penguintech.io/elder/flask-backend
  newTag: latest
configMapGenerator:
- behavior: merge
  literals:
  - LOG_LEVEL=INFO
  - RELEASE_MODE=false
  name: elder-config
labels:
- includeSelectors: true
  pairs:
    environment: beta
